# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandlogin', '0002_auto_20161216_1745'),
        ('products', '0002_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(related_name='user_products', to='regandlogin.User'),
        ),
    ]
