# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(default=1, related_name='user_products', to='regandlogin.User'),
        ),
    ]
