# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandlogin', '0002_auto_20161216_1745'),
        ('products', '0005_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(to='regandlogin.User'),
        ),
    ]
