# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regandlogin', '0007_auto_20161216_2110'),
        ('products', '0007_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user__product', to='regandlogin.User'),
        ),
    ]
