# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_user'),
        ('regandlogin', '0002_auto_20161216_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(related_name='user_product', to='products.Product'),
        ),
    ]
