# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandlogin', '0003_user_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(related_name='user__product', to='products.Product'),
        ),
    ]
