# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_user'),
        ('regandlogin', '0005_auto_20161216_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish',
            field=models.ManyToManyField(related_name='user__wish', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(related_name='user__product', to='products.Product'),
        ),
    ]
